version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
    - "8000:8000"

  nginx:
    build: ./nginx
    volumes:
      - static:/static
      - /data/certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - django_gunicorn
    

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  static: